server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://120.26.8.78:3310/shirojwt?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    # redis
    host: 120.26.8.78
    port: 6379
    password: lzf1697712297.
